export const data = [
	{
		id: 1,
		name: 'Links',
		classname: 'link-underline',
	},
	{
		id: 2,
		name: 'Portfolio',
		link: 'https://ousmanebarry.ca/',
		target: '_blank',
		rel: 'noopener noreferrer',
	},
	{
		id: 3,
		name: 'Github',
		link: 'https://github.com/ousmanebarry/',
		target: '_blank',
		rel: 'noopener noreferrer',
	},
	{
		id: 4,
		name: 'LinkedIn',
		link: 'https://www.linkedin.com/in/barry-ousmane/',
		target: '_blank',
		rel: 'noopener noreferrer',
	},
	{
		id: 5,
		name: 'Mail',
		link: 'mailto:kegnekobarry822@gmail.com',
		target: '_blank',
		rel: 'noopener noreferrer',
	},
	{
		id: 6,
		name: 'Featured Projects',
		classname: 'project-underline',
	},
	{
		id: 7,
		name: 'Wiki Search',
		link: 'https://wiki-search-web.netlify.app/',
		target: '_blank',
		rel: 'noopener noreferrer',
	},
	{
		id: 8,
		name: 'Random Quote Generator',
		link: 'https://random-quote-generator-web.netlify.app/',
		target: '_blank',
		rel: 'noopener noreferrer',
	},
	{
		id: 9,
		name: 'Akinator Discord',
		link: 'https://github.com/ousmanebarry/akinator-discord',
		target: '_blank',
		rel: 'noopener noreferrer',
	},
	{
		id: 10,
		name: 'Typeracer Bot',
		link: 'https://github.com/ousmanebarry/typeracer-bot',
		target: '_blank',
		rel: 'noopener noreferrer',
	},
];
